apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ah3qe3l7q-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f6aaa3afca.v2cn.p3.openshiftapps.com/rhtap/rhtap-qe:6cad3121b4c842b5344a659ad3212c17e0ded2e5@sha256:00b90b0fd2e16ed82c65ae8f142451b391bc529fc9211dee5ba52897b1f1048f
          name: container-image
